apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: release
resources:
  - ../base/podinfo
  - ../base/api-chart
patchesStrategicMerge:
  - podinfo-values.yaml
  - api-chart-values.yaml
