apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../base/podinfo
  - ../base/api-chart
namePrefix: production-
patchesStrategicMerge:
  - podinfo-values.yaml
  - api-chart-values.yaml
