apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-chart
spec:
  chart:
    spec:
      version: ">0.0.1"
  values:
    environment: staging
    host: staging.api
    image: public.ecr.aws/a6o8o7v2/api-image:0.0.1 # {"$imagepolicy": "flux-system:api-chart"}
