apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-chart
  namespace: apps
spec:
  chart:
    spec:
      version: ">0.0.1"
      valuesFiles:
        - values.yaml
  values:
    environment: staging
