---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-chart
  namespace: staging
spec:
  imageRepositoryRef:
    name: api-image
  policy:
    semver:
      range: 0.0.x
