apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base/podinfo
  - ../base/api-chart
namePrefix: staging-
patchesStrategicMerge:
  - podinfo-values.yaml
  - api-chart-values.yaml
