apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base/podinfo
  - ../base/api-chart
patchesStrategicMerge:
  - podinfo-values.yaml
  - api-chart-values.yaml
  - image-automation.yaml
  - image-policy.yaml
  - image-registry.yaml
