apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base/podinfo
  - ../base/api-chart
  - image-automation.yaml
  - image-policy.yaml
  - image-repository.yaml
patchesStrategicMerge:
  - podinfo-release.yaml
  - api-chart-release.yaml
