---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-chart
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-chart
  policy:
    semver:
      range: 0.0.x
